### ISSUE TITLE
Make decisions on the look

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#33] opened 2017-10-23 00:27 UTC
I think certain parts of the visual design should be decided beforehand, at least for elementary OS.

For example, I would personally want the text shadow on by default if I were a user downloading this from the AppCenter and turning it off would probably not even cross my mind. It fits well with Wingpanel and elementary's look in general and it also makes it easier to read.

I think the label color option might be better if it were eventually replaced with item labels automatically adjusting their colors based on whether it's dark or bright behind it (possibly including the panel behind the icon). It's likely the main reason for changing the label color between black or white anyway. This is what Wingpanel does when you change the wallpaper. Try changing your desktop to pure white. The text turns dark grey.

This is not to say remove all customisation, for example I think the current panel color selection should certainly stay. The new colors (based on elementary's new color palette) are a nice selection. It might eventually be necessary to have a preferences dialog for something (for example, rules on where certain types of files/folders go when dropped on desktop). See [my comment here](https://github.com/spheras/desktopfolder/issues/28#issuecomment-338519229).

My argument is that we should decide on how certain parts of the application look and function and set them in stone instead of overloading the user with millions of customisation options.

This is mostly from a elementary OS user's perspective. Perhaps this is also about deciding whether to make elementary OS the first-class citizen or not. Should this software cater to both elementary and GNOME users? Or should it be mostly for elementary users? GNOME already has a desktop you can enable with dconf/gsettings, but it doesn't have panels. elementary doesn't have any implemented desktop.

The points I have in mind specifically are:
- Should all labels have text shadow?
- Should item labels be bold or not?
- To what extent should the color of the panels allow customisation (custom colors)?
- Should notes have a square pattern or not? (they look less like sticky notes however)
- Should elementary OS be the main focus of this app?

What's everyone's thoughts on this?

**Comment by spheras** [comment] 2017-10-23 16:59
Yeah, a good conversation! I think we must differentiate between:

- **Default values configuration** (what values should be put by default) (and try to respect when loading from old desktopfolder versions)
- **Easy Configuration** (configuration that can be done easily, just opening the popup)
- **Hard Configuration** (configuration that can be done in a setting window)
- **No configuration** at all

I agree with the philosofy of try to reduce the configuration as much as possible, but, what Linux in general makes me happy is the possibility to configure as deep as I want. I mean, this is not the 100% of users, only a certain group of users want (need) to configure small/detail things.  In the case of Desktop Folder, the visualization part is very very important. People loves their desktop and how it looks. You know there are a lot of people pushing screenshots of their desktops, and this kind of users want (need) to select the perfect color, the perfect shadow, the perfect, transparency, the perfect font, and so on.

For instance, the case of shadow or bold. I love both. Why? because it depends a lot on the background picture you have selected, mainly if it is darker or lighter. If it is possible, I prefer to avoid shadows, because I love flat designs (and a lot of people also), but yes, it is a perfect solution for other cases... So... I need both, and I need to have a place to configure it. Is this for all the people? Probably no. I love two clicks, hate one click, I prefer windows style controls (right minimize, maximize, close), ... What I do after a fresh install of elementary is to install Tweaks, and thats why Tweaks is a success. Every body needs Tweaks? No, but at least you have a way to configure that. A similar reason is the existence of Desktop Folder itself. Probably elementary team design concept forbide the use of the desktop in an old style way, probably (I don't know) they want a clean desktop, but not all the people thinks the same, and, in my opinion, thats is beautiful, that is freedom.

hehe, so, I propose:

- rethink default values
- decide what configuration is easily done (ie. popup)
- make a settings window for the heavy configuration.

More configuration needed in the future: Custom color, Custom transparency, Font, Textures, ...

Regarding automatic configuration, It is a good idea, the problem is to find how to do it :D, but in principle it is a good (configured :D) purpose.

**Comment by aljelly** [comment] 2017-10-26 04:17
I had an idea: instead of creating settings for each thing to customise, how about allowing the user to edit the CSS themselves via a custom CSS page? For example, Notes-Up has this sort of page for the viewer. In that way, if someone wanted to edit how the app looked, they can change whatever they like. It would probably be called "style modifications" or something.

The advantage of providing a custom CSS page is that it means we don't have to create all the controls for every single thing the user might want to change (which would likely become a mess anyway) while giving the user maximum customisation.

We could link to a page on this GitHub repository's wiki page with some guidance for less technical users. We should also include a list of the relevant class names somewhere, probably on another wiki page.

We could make an initial template with commented out parts of code and explanations, for common things people might want. It might look something like this:

```css
/** This section is for customising how the application looks.
If you want to enable a part of the code, remove the slash and the star at the start and the end of the code (this is called "uncommenting").
Text marked with two stars are explanations and not code, so don't uncomment them. **/

.df_folder .df_label {
    /** Remove or override text-shadow: **/
    /* text-shadow: none; */

    /** Override label colors to always be a certain color, like black: **/
    /* color: black; */

    /** Make all labels bold: **/
    /* font-weight: bold; */

    /** Override the font: **/
    /* font-family: "Comic Sans MS"; */
}
```

We could also provide snippets. Snippets would paste blocks of code without losing what's currently in the text entry box. I imagine it could be something like a dropdown menu below the custom CSS.

For example, the snippet "Change panel background-color to green" could paste:

```css
.df_folder {
    background-color: green;
}
```

I also install Tweaks, but I recently decided to try leaving single click on. I've mostly got used to it. It's slightly more awkward to select things but it's nice to be able to click on something and open it. It might make most sense for non-technical people or people who aren't very good with computers. We have to remember that people who hardly know anything about computers could potentially be using this app.

**Comment by spheras** [comment] 2017-10-26 21:42
Yes, the idea is good for the finest setting, but it seems difficult to implement and to use (much more if you think in individual panel configurations, not global), it is much more easy to show the setting file (i.e. .desktopfolder json file) and edit it. I've just seen the Notes-up, and it have two advance settings, the editor and view. Here we have the same problem, not everything can be configured via css, you still need an "editor view".

Really, I hope this is not necessary, I'm afraid you think we will have thousands of settings :D. Maybe what we could do first is to decide what is the minimum/maximum configuration allowed. In my opinion (in the case of Panels, which seems the most diffficult), what we need is:

1. **Background Color** (and add at the end of the currentcolors boxes an interrogation ?, when the user click the ? a selection color +transparency appears)
2. **Front Color** just like now, or maybe adding a third option with Automatic Mode as you suggested
3. **Shadow Text** (I can consider this option to be removed and apply shadow always, because really 90% of cases is OK in my opinion)
4. **Bold Text**: I like usually bold texts for files (in fact, it was bold at the begining), but not always
5. **Align to Grid**, seem an important and asked setting

And That's all we need in my opinion, only 5 parameters. I don't mind if this parameters are shown at the popup, or a submenu, or in a window settings (like the Notes-Up editor settings).  I know there a lot of more configuration. For instance, what, in my opinion, is not needed to be configured:

- single/double click: use the files configuration  (if there is not Files setting, use double click as default)
- show hidden files  (I think that panels shouldn't show hidden files)
- header (I think all panels should have headers, and the size should be what ever we decide)
- Font Family (I think we should force to use a font family)
- Shadow distance (I think we should force to use a shadow distance)
- ...

**Important**: this is my opinion.. for that reason, I don't mind to have an advanced setting mechanism (via css, via window setting, via json, whatever) to configure others settings, or all the settings.

How do you see this. For example, what are the preferences you think should support the app? And what preferences shouldn't be supported?

**Comment by aljelly** [comment] 2017-10-27 21:18
I expect we're likely going to have two forms of settings: global preferences and individual panel properties/settings, so I think we'll have to decide what settings are applied to individual panels and what settings affect the whole application. For example, custom background color will likely be kept as a per panel setting.

I started the wiki and put some thoughts on how we could structure the options and menus on a wiki page [here](https://github.com/spheras/desktopfolder/wiki/Menus-&-Options-Layout-(draft)). Feel free to edit it (previous revisions of the page are preserved). The default permissions seem to be that only contributors can edit it.

**Comment by spheras** [comment] 2017-10-27 22:01
My comments there @aljelly, very good job

**Comment by aljelly** [comment] 2017-11-06 11:57
Putting this here (also maybe we should continue discussing this here as the wiki doesn't send notifications):

I think we should make text-shadow and text-bold gsettings options that apply to all objects. Is there anyone who would want to mix these options?

(We could put it under com.github.spheras.desktopfolder.appearance or something)

**Comment by spheras** [comment] 2017-11-10 18:44
I would like to mix, but if no body else wants.. well, I can adapt

**Comment by jica** [comment] 2017-11-10 21:08
At this moment, I think that the application should show all the options easily.

This is a new app and people who install it are not going to search the options, so it should show how customizable it is.

**Comment by spheras** [comment] 2017-12-26 09:01
Closing this issue. Let's open a new one if necessary for the next release.

**Closed by spheras** 2017-12-26 09:01 UTC
Labels: meta, Priority: High, Status: In Progress
