### ISSUE TITLE
Move files into folder and rectangular drag to select multiple files

### ISSUE THREAD

**Issue by danieleiervo** [spheras/desktopfolder#118] opened 2018-10-19 23:03 UTC
Hi! I installed desktopfolder an hour ago. I'm missing the possibility to just select a bunch of files on the desktop by dragging the mouse and then move them into a folder. It isn't even possible to select just one file and move it into any folder. Is it possible to add these features?

**Comment by spheras** [comment] 2018-10-20 00:13
Hi @danieleiervo. You can do that from outside desktopfolder... I mean, you can open Files application, select a bunch of files and drop them into a panel. (it is there an issue reported to improve the location where the files appear).  You can't select multiple files/folders inside desktopfolder by the moment.

Yeah, it could be a good feature for the future. To be honest, currently I'm practically alone in the project and I'm only focused on the most important bugfixing and features.  Anyway, this seems a good feature to take into account or perhaps to anyone who could help to add that feature to the project.

Thanks for reporting!

**Comment by eljefuri** [comment] 2018-11-10 12:57
Hi @danieleiervo I'm with you on this feature request and definitely think that _at least_ the rectangular "rope" select (if only to move the icons in a group) would a useful first step. @spheras is it helpful to have some bounties setup for some of these issues?

**Comment by spheras** [comment] 2018-11-10 21:32
Hello @danieleiervo. I'm not experienced in any bounty system. Could you give me some hints about that?

**Comment by spheras** [comment] 2019-01-27 00:47
Ok, I pushed a first version of multiselect.  This is an important change that could affect to other issues. I tried to solve most important and now seems to work, but... we need to check a lot.  @fossfreedom, I haven't check yet on UB, if possible, take a look, I'll check too.

**Comment by spheras** [comment] 2019-01-28 14:47
Ok, thanks for this good info @fossfreedom. I'll work to fix them.

**Comment by spheras** [comment] 2019-01-31 00:54
@fossfreedom, most of the points you commented should be fixed now.

**Comment by fossfreedom** [comment] 2019-01-31 11:08
Started from a fresh ~/Desktop folder and started com.github.spheras.desktopfolder

1.  Right click. Create a new folder.  Right click - create a new file.  Press CTRL and drag to the folder.  A new file unexpectedly gets created on the desktop **--> probably should be a new issue?**
2.  Minor issue: Right click and create a folder on the desktop.  Right click and create a panel. Right click and create another folder on the desktop.  CTRL + Drag both folders onto the panel.  Delete the two folders on the desktop. Select both folders in the panel and CTRL and drag to the desktop.  Sometimes the folders are place vertically (correct).  Sometimes they appear random across the screen.
3.  Select two files or two folders or a file + folder. Right click. Rename menu option is available. Think it should be hidden/menu option disabled in this initial version and maybe a future enhancement would be to handle multiple renames?
4. Have one file on the desktop called Test.txt. Have a file called Test.txt in another folder C:\Pictures. In Nemo drag the Test.txt that is on C:\Pictures to the desktop. nothing happens. In the terminal there is a correct message "File exists" - should I guess be displayed to the user - or possible offered an option to overwrite the file? **--> probably should be a new issue?**
5.  Right click on two selected folders in a panel - the change icon menu option is available.  Choosing an icon only changes one of the folders selected. Think it should be hidden/menu option disabled in this initial version and maybe a future enhancement would be to handle multiple icon changes?
6. Similarly Right click on two selected folders in a panel - the properties menu option doesnt handle multiple selections. Think it should be hidden/menu option disabled in this initial version and maybe a future enhancement would be to handle properties of multiple selected components?
7. On a panel choose the upper right properties button.  Dialog appears.  Then click close.  You'll notice that the properties button remains highlighted.  Clicking anywhere on the panel activates & shows the Dialog **--> probably should be a new issue?**

**Comment by spheras** [comment] 2019-01-31 22:53
1. Do you expect to move the file inside the folder, don't you? In that case, yes, it is better a new issue to improve that (I mean, nothing to do with a rectangular drag to select multiple files issue)
2. I couldn't reproduce the problem, I will try again.
3. Ok, I will disable rename.
4. Yes, better a new issue to improve that.
5. Ok, I will disable the change icon option.
6. I will disable the properties menu option when multiselection.
7. Ok, I see. Better a new issue (just a minor issue)

**Comment by spheras** [comment] 2019-02-04 10:10
I'm closing this issue. Please feel free to reopen in case you see something new to deal with about this issue.

**Closed by spheras** 2019-02-04 10:10 UTC
Labels: enhancement
