### ISSUE TITLE
Align panel items to grid

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#11] opened 2017-10-18 02:11 UTC
Currently, there is no alignment grid for panel items. An alignment grid feature would make it easy to position items. This could include automatically stacking icons to the beginning of the panel.

Ideally there would be two options to configure:
* Enable or disable grid alignment
* Automatically align icons (to the beginning of the panel)

Perhaps look at how [Files](https://github.com/elementary/files) does it?

**Comment by spheras** [comment] 2017-10-18 16:36
Yes, thanks @aljelly , @jica  and I discussed about this some days ago about this feature, seems very useful. Probably we will do it for the next milestones, it is a good idea for the next features.

Thinks to think:

- how should the user interact with the panel to configure that (popup, mini butons at header?)
- should the icons be moved automatically to a grid position and after that you can again move wherever you want, or limit it to a valid position (grid) when the grid is activated.
- In fact we have already a grid alignment, just the problem is that the sensitivity is 4 pixels, but you can realize that you move the icon 4 pixels ahead, we can increase easily the number of pixels (by configuration or something). @aljelly, you can modify the const SENSITIVITY in ItemView.vala file to check this.

**Comment by aljelly** [comment] 2017-10-20 06:35
You're right, I can see it's snapping just slightly. Perhaps this is how it should work:

- When dragging an item, instead of moving the item around as it does now, it shows a ghost/helper (similarly to Files and Windows 7).
- However, in contrast to how Files does it, the ghost is positioned to the mouse exactly where you dragged it. This would help with exact positioning when grid is disabled (i.e. 1 pixel grid).

I think probably right clicking on the desktop and clicking "Align icons to grid" (along with "Automatically arrange icons") is probably the best way to do it. It's the most simplest option, it's convenient to access, and it avoids a settings panel.

If the "Align icons to grid" context menu option is checked, show "Automatically arrange icons" as an checkbox option beneath it. If "Align icons to grid" is unchecked, don't show "Automatically arrange icons".

What Windows 7 looks like for reference:

![draganddropwindows2](https://user-images.githubusercontent.com/10395308/31807719-a8067ae4-b567-11e7-99d6-77b78c99de2d.gif)

**Comment by spheras** [comment] 2017-10-22 15:09
This is the current status of the grid issue. Maybe we could close it as it is now and think again the needs to improve.
![test-grid](https://user-images.githubusercontent.com/3862933/31863266-b8b08796-b74b-11e7-9a3b-24248a730a9e.gif)

**Comment by spheras** [comment] 2017-10-23 17:28
I close this issue. For new improvements about this feature we will create new issues.

**Closed by spheras** 2017-10-23 17:28 UTC
Labels: enhancement, help wanted
