### ISSUE TITLE
Photo reappears when deleting all other desktop windows and panel over desktop is disabled

### ISSUE THREAD

**Issue by aljelly** [spheras/desktopfolder#160] opened 2018-11-17 22:25 UTC
### System Information
Version: 1.0.10 from AppCenter
OS: elementary OS Juno 5.0

### Steps to reproduce

1. Disable Panel Over Desktop in Properties. `killall com.github.spheras.desktopfolder` and relaunch Desktop Folder.
2. Add a desktop photo.
3. Remove every other desktop folder window except the photo you added.
4. Remove the desktop photo.
5. The "My First Panel" folder will appear. If the photo hasn't reappeared, try moving the panel.

### Result

The photo you deleted will reappear. If you try to remove the photo again, it might reappear a second time.

**Comment by spheras** [comment] 2018-11-17 22:36
I can't reproduce this error, tried several times. mmm Maybe some step missing?

**Comment by aljelly** [comment] 2018-11-17 23:04
Weird. Occasionally it doesn't happen but it happens mostly consistently for me. Maybe try loading different photo files.

When it does happen the .desktopphoto file temporarily disappears and then reappears in the Desktop folder. I don't see any strange messages with `G_MESSAGES_DEBUG=all` apart from it saying it loaded the .desktopphoto settings again.

**Comment by aljelly** [comment] 2018-11-18 01:12
Might be some sort of race condition?

**Comment by spheras** [comment] 2018-11-18 01:44
mm no idea. I will try to reproduce this later again.

**Comment by spheras** [comment] 2018-11-21 23:39
no way to reproduce :(, could debug what is happening?

**Comment by spheras** [comment] 2019-01-17 10:19
I think this is solved in the current master branch. I'm closing it, please, reopen if necessary.

**Closed by spheras** 2019-01-17 10:19 UTC
Labels: Priority: Low, Status: Needs Confirmation, bug
