### ISSUE TITLE
App keeps resetting

### ISSUE THREAD

**Issue by ar0ra1** [spheras/desktopfolder#97] opened 2018-01-15 05:24 UTC
So I just booted in to find out all my notes are lost.  
Only 1 note on the panel with just `Lorem Ipsum` written on it.  

I also had a picture on my desktop, now when I check `Trash` it is there but I can't restore it.  
So I killed the application, restored and re-launched the application and it resends the image and other things to `Trash`.

**Comment by spheras** [comment] 2018-01-15 06:53
Hi @ar0ra1.  Have you modified the .desktopnote json file?  When the application try to open the file, and find a wrong format (i.e. something missed inside), it send to trash because it is unreadable.  Probably that's the reason.  Could you attach here the file sent to trash to see what happens?

**Comment by ar0ra1** [comment] 2018-01-15 13:46
No point of attaching here.  
They are all 0 bytes in size.  
Nothing in them.

**Comment by spheras** [comment] 2018-01-16 06:47
Ok. It sounds very strange for me. I can't reproduce. I have some questions to try to reproduce:

- What version of desktop folder are you using now? Did you updated to the last version?
- Is this issue related with #96? or derived from that
- Did you modified manually the json files?
- So, initially you had some panels and/or notes and/or pictures? do you remember what exactly?
- Do you remember something strange you did before the last boot when everything disapeared?
- Can you reproduce it again? Can you detail the steps to reproduce it or any idea about how to reproduce?

thanks

**Comment by ar0ra1** [comment] 2018-01-16 08:54
- Latest (1.0.5)
- Not related to #96 
- No
- 1 note and 1 picture
- Boot failed (last system state was hibernate, and hence that could have caused it)

**Comment by Abhinav1217** [comment] 2018-02-01 13:50
Notes are resetting after reboot. I had two notes, "Things to do", and  "Reminder" both had few lines written with them. But after reboot, Only one note was there "Things to do" and its content was replaced by "Lorem Ipsum" only.

**Comment by spheras** [comment] 2018-02-01 17:01
Hi @Abhinav1217. Thanks for reporting. I'm trying to reproduce this kind of effect without success. Probably I'm not doing exactly what is needed. Maybe yout know how to reproduce the problem. Could you explain, or try, to reproduce it?

More questions: The only reason in my head that explain why the notes are resetted is because the note component try to read the note file (filename.desktopnote at the desktop folder) and the json inside is not parseable. In this case, because the json is not understable, the application throw to the trash the bad file and create a new one with default content.
**First**: Could you check the trash to see if there is the original file?
**Second**: Have you modified manually some way the json??

Any idea about how to reproduce the problem could help a lot.  Thanks!

**Comment by Abhinav1217** [comment] 2018-02-02 07:29
**_First_** 
There are files with title of notes, but they are all 0 byte files. Basically just empty file names. So I would say original file names but _not the original files_ themselves.
```
abhinav@Abhinav-ele:~/.local/share/Trash$ tree
.
├── expunged
├── files
│   ├── My First Panel
│   ├── Things to Do.2.desktopnote
│   ├── Things to Do.3.desktopnote
│   ├── Things to Do.4.desktopnote
│   ├── Things to Do.5.desktopnote
│   └── Things to Do.desktopnote
└── info
    ├── My First Panel.trashinfo
    ├── Things to Do.2.desktopnote.trashinfo
    ├── Things to Do.3.desktopnote.trashinfo
    ├── Things to Do.4.desktopnote.trashinfo
    ├── Things to Do.5.desktopnote.trashinfo
    └── Things to Do.desktopnote.trashinfo

4 directories, 11 files

abhinav@Abhinav-ele:~/.local/share/Trash$ cat files/Things\ to\ Do.2.desktopnote 

abhinav@Abhinav-ele:~/.local/share/Trash$ ls -la files/
total 12
drwx------ 3 abhinav abhinav 4096 Feb  2 12:37 .
drwx------ 5 abhinav abhinav 4096 Feb  2 12:37 ..
-rw-rw-r-- 1 abhinav abhinav    0 Jan 26 13:10 .2.desktopfolder
-rw-rw-r-- 1 abhinav abhinav    0 Feb  1 20:06 .3.desktopfolder
-rw-rw-r-- 1 abhinav abhinav    0 Jan 26 13:10 .desktopfolder
drwxr-xr-x 2 abhinav abhinav 4096 Jan 25 14:44 My First Panel
-rw-rw-r-- 1 abhinav abhinav    0 Jan 31 22:38 Things to Do.2.desktopnote
-rw-rw-r-- 1 abhinav abhinav    0 Feb  1 14:49 Things to Do.3.desktopnote
-rw-rw-r-- 1 abhinav abhinav    0 Feb  1 20:06 Things to Do.4.desktopnote
-rw-rw-r-- 1 abhinav abhinav    0 Feb  2 00:00 Things to Do.5.desktopnote
-rw-rw-r-- 1 abhinav abhinav    0 Jan 29 23:41 Things to Do.desktopnote

```

*_Second_* 
I am quite certain I haven't modified anything, This elementary is clean install about 2 weeks ago, I installed this software via appcenter about 2 days later. My dev system is fedora so only thing I have installed on elementary (other then the basics stuffs)  are popcorn time to watch some shows and an old game via wine. Fedora is on separate partition and does not have access of any type on elementary partition. I haven't even configured my dotfiles yet. 

If you could tell me where notes should be stored, maybe I could do some digging. I am kind of free these days. I tried searching `.local` and `.config` but there is nothing regarding this app.  Icons on my panels are still there, so issue is only with notes as far as I encountered.

**Comment by spheras** [comment] 2018-02-02 07:34
Thanks for the info @Abhinav1217.  I will try to process this info during the weekend. Regarding the files storing the notes... everything is stored at the desktop folder: /home/youruser/Desktop.  You will find there:

- notename.desktopnote  for notes (inside a json)
- photoname.desktopphoto for photos
- folders, and inside a .desktopfolder for the panels

Thanks!

**Comment by Abhinav1217** [comment] 2018-02-02 07:34
P.S. There are 5 `Things to Do` files in the trash, I am not sure but maybe thats 1 file for each day. Thats about how long I have been trying to use notes feature. And I have a habit of starting system in morning and closing it straight  at night.

**Comment by Abhinav1217** [comment] 2018-02-02 07:45
Ok I found them in desktop. Just a thought, elementary is build upon gnome stack, and like gnome it does not like keeping stuffs on desktop. Gnome 3.26 is done away with desktop entirely, So I was thinking maybe there are some undocumented missing features or bugs introduced regarding desktop. Elementary does cherrypick some patches from gnome stack into pantheon shell. Can you trying having a backup at locations like `.config` and syncing it with your current location.

**Comment by spheras** [comment] 2018-02-03 08:58
well, it is just a folder (the application creates it). I don't think that the system is touching that folder, or files there, sincerely... but who knows! :smile:   By the moment I have tried to reproduce it, but ... nothing. I have restarted my laptop 30 times, and the note is still there. I've put a massive content on the note, and still there.. I've tried pasting a huge content on the note and trying to shutdown the laptop inmediatelly... but nothing.. the note is still there.

The point is that, it seems, some way, the note file have being saved as a 0 bytes file. Then, when the application starts, it try to load the note, but find a 0 bytes file.. so it send that to the trash and create a new one with the default content.  So.. the question is, why or who is storing a 0 bytes file.  Is something strange. I don't know.. Do you remember something special you did the last time the note was there? Maybe it is related with the content you wrote?? Did you interact with the note? ...  Have you tried to reproduce this again?

thanks

**Comment by Abhinav1217** [comment] 2018-02-05 10:25
I am confused too, Technically even if I do not enter single character, file should not be 0 byte. 
I actually tested this and saved my result for you.

```
abhinav@Abhinav-ele:~/.local/share/Trash$ ls -la ~/Desktop/
total 48
drwxr-xr-x  3 abhinav abhinav 4096 Feb  5 15:40 .
drwxr-xr-x 35 abhinav abhinav 4096 Feb  5 14:31 ..
-rwxr-xr-x  1 abhinav abhinav  271 Feb  4 13:45 Balance Game.desktop
-rw-rw-r--  1 abhinav abhinav  735 Feb  4 13:45 Balance Game.lnk
-rwxr-xr-x  1 abhinav abhinav  404 Jan 26 23:21 Counter-Strike v7.1.desktop
-rw-rw-r--  1 abhinav abhinav  268 Jan 26 23:23 .desktopfolder
-rwxr-xr-x  1 abhinav abhinav  295 Feb  4 13:45 Falco Freeware Website.desktop
-rw-rw-r--  1 abhinav abhinav  685 Feb  4 13:45 Falco Freeware Website.lnk
drwxr-xr-x  2 abhinav abhinav 4096 Feb  4 15:40 Games
-rw-rw-r--  1 abhinav abhinav  264 Feb  4 15:40 Test note (empty).desktopnote
-rw-rw-r--  1 abhinav abhinav 2199 Feb  4 15:40 Test Note ( Large ).desktopnote
-rw-rw-r--  1 abhinav abhinav  302 Feb  4 15:40 Test note ( small ).desktopnote

```
and next day as expected all the notes were missing except for a single template note. Unexpectedly, I thought It would be titled `Test note (small)` because it was the first note I made, but it was still Titled Things to do.
```
abhinav@Abhinav-ele:~/.local/share/Trash$ ls -la ~/Desktop/
total 40
drwxr-xr-x  3 abhinav abhinav 4096 Feb  5 15:54 .
drwxr-xr-x 35 abhinav abhinav 4096 Feb  5 14:31 ..
-rwxr-xr-x  1 abhinav abhinav  271 Feb  4 13:45 Balance Game.desktop
-rw-rw-r--  1 abhinav abhinav  735 Feb  4 13:45 Balance Game.lnk
-rwxr-xr-x  1 abhinav abhinav  404 Jan 26 23:21 Counter-Strike v7.1.desktop
-rw-rw-r--  1 abhinav abhinav  268 Jan 26 23:23 .desktopfolder
-rwxr-xr-x  1 abhinav abhinav  295 Feb  4 13:45 Falco Freeware Website.desktop
-rw-rw-r--  1 abhinav abhinav  685 Feb  4 13:45 Falco Freeware Website.lnk
drwxr-xr-x  2 abhinav abhinav 4096 Feb  4 15:53 Games
-rw-rw-r--  1 abhinav abhinav  270 Feb  5 15:54 Things to Do.desktopnote
```

There is nothing unexpected in trash though
```
abhinav@Abhinav-ele:~/.local/share/Trash$ tree files
files
├── A new note.desktopnote
├── A new note.2.desktopnote
├── A new note.3.desktopnote
├── A new note.4.desktopnote
├── My First Panel
├── Test note (empty).desktopnote
├── Test note (empty).2.desktopnote
├── Test note (empty).3.desktopnote
├── Test Note ( Large ).desktopnote
├── Test Note ( Large ).2.desktopnote
├── Test Note ( Large ).3.desktopnote
├── Test note ( small ).desktopnote
├── Test note ( small ).2.desktopnote
├── Test note ( small ).3.desktopnote
├── Things to Do.2.desktopnote
├── Things to Do.3.desktopnote
├── Things to Do.4.desktopnote
├── Things to Do.5.desktopnote
├── Things to Do.6.desktopnote
├── Things to Do.8.desktopnote
├── Things to Do.9.desktopnote
├── Things to Do.10.desktopnote
├── Things to Do.11.desktopnote
├── Things to Do.12.desktopnote
└── Things to Do.desktopnote

1 directory, 24 files
```

**Comment by Abhinav1217** [comment] 2018-02-05 10:39
There is a thing which I Just noticed while posting above, 
Take a look at `ls -la ~/Desktop` output, Correct me if I am wrong but I think the column `Feb 4` is last modified timestamps.

 Which is really weird because I haven't touch the files at least from feb 2, Now Counter strike desktop icon was self generated by script and did not belong to your app. it has not changed since then. But rest of the other icons, I created them from your app and apparently Its time stamp is updating daily.  I am bit confused if it is last used or last modified timestamp or some other time stamp, But I have played only one game this weekend so other timestamps should not change. 

Maybe I am just getting confused on what type of timestamps it is supposed to be.

**Comment by spheras** [comment] 2018-02-05 22:16
Yes, it is very strange. I have no idea why most files are from Feb 4 if you haven't touched them.  The application modifies only the .desktopnote .desktopfolder and .desktopphoto files.  It seems you can reproduce the problem whenever you need, so... could you write a note (in the language you are writing those notes, perhaps the language is important?), and attach here the .desktopnote file created?  Maybe I can reproduce the problem too.. Or if its possible, just rename your current /home/user/Desktop to Desktop_tmp or similar, to create a new one, with some notes, and zip it. Just to try to reproduce it in my laptop.

thanks for all the info

**Comment by Abhinav1217** [comment] 2018-02-06 09:06
Language is plain english US. Keyboard setting is english. 

Here is a desktop note I created just now. 
```
{"resolutions":[{"resx":1920,"resy":1080,"x":110,"y":110,"w":717,"h":689}],"resx":1920,"resy":1080,"x":110,"y":110,"w":717,"h":689,"name":"Testing","bgcolor":"df_yellow","fgcolor":"df_dark","clipcolor":3,"texture":"","text":"This is a test note.\nAnd a new line.\n\nNote size is big\n\nGood Luck","on-back":true,"version":3}
```
I haven't prettified it to avoid human error.
Here is my current desktop folder
`https://file.io/1xBN1X`

**Comment by Abhinav1217** [comment] 2018-02-07 05:25
Ok, Now I am certain the timestamp is an irregularity. And most likely cause of this issue. I actually found  stackoverflow question, and there, answer confirmed that the time stamp is Last Modified time stamp.  


Here is what I just did to confirm it. 
1. In pantheon files, I switched to list view, It has a column for modified time stamp. Look at the first screenshot. Notice the modified column, It is approximately the time I started my system.
![Uploading Screenshot from 2018-02-07 10-11-10.png…](First Screenshot)


2. Then I used `ps -aux | grep "desktopfolder" to find and kill your app process.
```
abhinav@Abhinav-ele:~/Desktop$ ps -aux | grep "desktopfolder"
abhinav  11522  0.0  0.0  32112  1020 pts/1    S+   10:32   0:00 grep --color=auto desktopfolder
abhinav  19029  0.0  0.4 529436 36684 ?        Sl   10:11   0:00 com.github.spheras.desktopfolder
abhinav@Abhinav-ele:~/Desktop$ kill 19029
abhinav@Abhinav-ele:~/Desktop$ ps -aux | grep "desktopfolder"
abhinav  19565  0.0  0.0  32112   976 pts/1    S+   10:33   0:00 grep --color=auto desktopfolder
```
3. I relaunched your app and took another screenshot of desktop folder in pantheon files. You will noticed the modified time is changed to current time, when I launched the app. New time would made sense if this was last accessed timestamp. But since it is modified timestamp, I guess the application is modifying the files when it is reading it.  
![Uploading Screenshot from 2018-02-07 10-11-59.png…](Second Screenshot)

We were missing this on terminal because it just showed the date, not the time of the date. 

My guess is that this application is creating new panels and icons and notes and stuffs everytime it is launched. Which usually should means everytime computer is restarted. Which might mean why I don't get my notes retained _next day_ . But was available when I was restarting this multiple time to test this gather information for you. My usual habit is to start system in the morning and close it at night. I don't close it in the middle of day. My guess is ( and I should be able to confirm it tomorrow )  When I create a note, It is saved with todays timestamp, but when I restart system _next day_ and application checks for all the notes and panels, It thinks note is corrupt because of mismatched timestamp and sends it to trash and create new note with lorem ipsum instead.  

Anyways I am just assuming this behavior, because I haven't gone through your code ( honestly, It has been long time I worked on C/C++ or C# and vala is supposed to be C/C# like language for gnome stack. ) So I am purely blackbox testing it.

Here is something I will do next, I will create a new note today, and gather data on all 3 timestamps ( created on, last accessed, modified ). Do some further app restarting and tomorrow ( if I am right, I should not retain notes ),  Collect timestamps, and report it to you. I can try changing the time and date on my system to simulate changed date but I am doubtful it will work. Can  you work with this angle meanwhile.

**Comment by spheras** [comment] 2018-02-07 06:54
No, that's normal. What I said is that the application only touch it application files:

- .desktopfolder
- *.desktopnote
- *.desktopphoto

Those files are modified a lot of times by the application. It is normal to find them modified because all the maitained information is there. What is not normal is to find the other files modified. In your first "time capture" you had these files:

```
abhinav@Abhinav-ele:~/.local/share/Trash$ ls -la ~/Desktop/
total 40
drwxr-xr-x  3 abhinav abhinav 4096 Feb  5 15:54 .
drwxr-xr-x 35 abhinav abhinav 4096 Feb  5 14:31 ..
-rwxr-xr-x  1 abhinav abhinav  271 Feb  4 13:45 Balance Game.desktop
-rw-rw-r--  1 abhinav abhinav  735 Feb  4 13:45 Balance Game.lnk
-rwxr-xr-x  1 abhinav abhinav  404 Jan 26 23:21 Counter-Strike v7.1.desktop
-rw-rw-r--  1 abhinav abhinav  268 Jan 26 23:23 .desktopfolder
-rwxr-xr-x  1 abhinav abhinav  295 Feb  4 13:45 Falco Freeware Website.desktop
-rw-rw-r--  1 abhinav abhinav  685 Feb  4 13:45 Falco Freeware Website.lnk
drwxr-xr-x  2 abhinav abhinav 4096 Feb  4 15:53 Games
-rw-rw-r--  1 abhinav abhinav  270 Feb  5 15:54 Things to Do.desktopnote
```

What I said is that the application doesn't touch anything but its own files (as I said, .desktofolder, .desktopnote and .desktopphoto). You can see that .desktop and .lnk files were modified on 4Feb... and, If I'm not wrong, you said that you hadn't modified those files since 2Feb. Is that correct?

Thanks for all the info. I will try to get some time these days to find the problem. One idea I had in my mind is to compile a version for you and change the folder /home/user/desktop to other, just to see if the problem persist or it is just a problem for that folder in your computer.  I will keep you informed. Thanks again.

**Comment by spheras** [comment] 2018-02-07 07:09
One question @Abhinav1217. Is your elementary installed in a virtual box, vmware or similar?

**Comment by Abhinav1217** [comment] 2018-02-08 09:33
No Its on HDD. sda2 to  be specific. sda1 is efi partition and sda3 is fedora.

**Comment by spheras** [comment] 2019-01-17 10:54
I'm closing this issue (ordering and cleaning issues), we can't reproduce to solve it. Any help to solve this is more than welcome, please, if you have a new clue don't hesitate to reopen again.

**Closed by spheras** 2019-01-17 10:54 UTC
Labels: help wanted
