### ISSUE TITLE
Major Glitch when dragging file

### ISSUE THREAD

**Issue by CodeManS99** [spheras/desktopfolder#14] opened 2017-10-18 17:13 UTC
After failure of the link to a folder feature, I tried to drag and drop the folder into a panel. This caused the whole system to glitch out. I had to control of left click or right click and the enter key was not usable. Also, ctrl + Q was not closing any programs. I would send the crash data, but I don't know how to do that since the system becomes unusable after the crash.

**Comment by spheras** [comment] 2017-10-18 18:31
Hello @CodeManS99, thanks for reporting. Could you try to explain this issue a bit more? I don't understand the first part: "After failure of the link to a folder feature, I tried to drag and drop the folder into a panel.".
Could you give us the steps to reproduce the problem?

thanks!

**Comment by CodeManS99** [comment] 2017-10-18 19:48
I opened up a panel, put two apps in it. After that, I right clicked in the panel and select link to folder, but it wasn't allowing me to select it. After that, I opened up a files window and proceeded to try and manually drag the folder into the physical panel (not the folder for the panel) and that's when the glitch happened. My cursor then locked on the hand and green plus indicating that it froze while trying to add the folder. After that I wasn't able to close or open anything except through super key shortcuts.

**Comment by Philip-Scott** [comment] 2017-10-19 14:54
I think the problem is that dragging a folder to the Panel is actually moving it's conents, so you might be having a problem with moving folders with more folders inside, or something like that

**Comment by spheras** [comment] 2017-10-19 16:41
Yes @Philip-Scott, that's correct. Currently you can't drag a folder to a panel because of a recursive copy problem (I will create an issue for that).. but it just do nothing (a debug error is shown only).. I can't figure out how to hang the system as comented.

@CodeManS99, I'm trying to reproduce the issue without success. What I did is:

1. Created a new Panel (empty)
2. From slingshot I dragged two apps to the panel correctly
3. I right clicked onto the panel, showing the popup
4. I selected the "New link to folder" option
5. I selected a folder, and the link to the folder was correctly created (that seems a difference with you)
6. I tried to drag from files window some folders, without success (as I said, currently you can't drag a folder to a panel, this is a different issue, but I can't see a glitch after that)

I something wrong?

**Comment by aljelly** [comment] 2017-10-29 05:32
I tried this and also didn't come across any issues. Because this is 10 days old and there's no further elaboration on this issue, I'm closing.

If there's anything more to add or you have new information, we'll reopen. Try running `com.github.spheras.desktopfolder` in the terminal and show us the output if you can reproduce it again.

**Closed by aljelly** 2017-10-29 05:32 UTC
Labels: help wanted, Status: Incomplete
